In [6]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path("C:/Toronto_Waste")   # ← explícito
CLEAN_DIR = BASE_DIR / "data" / "clean"

path = CLEAN_DIR / "population_context_city_level.csv"
print("Exists:", path.exists(), "|", path)

df = pd.read_csv(path)
df.head()

Exists: True | C:\Toronto_Waste\data\clean\population_context_city_level.csv

   YEAR (JULY 1)  0 to 14  15 to 64  65 Plus  TOTAL_CHECK
0           2024   802560   4694136  1049542      6546238
1           2025   788330   4603092  1076056      6467478

In [8]:
df.shape, df.columns.tolist()

((2, 5), ['YEAR (JULY 1)', '0 to 14', '15 to 64', '65 Plus', 'TOTAL_CHECK'])

In [7]:
BASE_DIR = Path.cwd().parent

In [9]:
df["TOTAL_CHECK"] - (df["0 to 14"] + df["15 to 64"] + df["65 Plus"])

0    0
1    0
dtype: int64

In [10]:
df.set_index("YEAR (JULY 1)")[["0 to 14","15 to 64","65 Plus","TOTAL_CHECK"]]

               0 to 14  15 to 64  65 Plus  TOTAL_CHECK
YEAR (JULY 1)
2024            802560   4694136  1049542      6546238
2025            788330   4603092  1076056      6467478